description = "Mânăstirea Călui se află pe malul Oltețului, în apropiere de Craiova, nu departe de comuna Oboga, comuna renumită pentru ceramica ei populară."
keywords = ["Manastirea Calui"]
favicon = "favicon/favicon.ico"
googleTagManager = "GTM-M36G9ND"
opengraph = "/og-image/manastirea-calui.jpg"
googleSiteVerification = "7r3xw3xpjbnnTKzMX51NEr43B9QLqJ5rceAQgamZDvM"

transpiler = 'libsass'

[author]
name = "Paul-Andrei Onac"
email = "onac.paul.andrei@gmail.com"
link = "mailto:onac.paul.andrei@gmail.com"

[footer]
[footer.info]
heading = "Investim în viitorul tău! <br>Proiect cofinanțat din Fondul European de Dezvoltare Regională prin Programul Operațional Regional 2014-2020"
text = "Conținutul acestui material nu reprezintă în mod obligatoriu poziția oficială a Uniunii Europene sau a Guvernului României"

[[footer.links]]
title = "www.inforegio.ro"
url = "https://www.inforegio.ro"

[[footer.links]]
title = "facebook.com/inforegio.ro"
url = "https://facebook.com/inforegio.ro"

[footer.contactInfo]
address = "Şos. Frații Buzești nr. 209, sat Gura Căluiu, comuna Călui, judeţul Olt"
street = "Şos. Frații Buzești nr. 209, sat Gura Căluiu, comuna Călui"
city = "judeţul Olt"
postalCode = "237291"
phone = "0249 / 421.026"
fax = "0246 / 214.081"
person = "Ieromonarh Macarie (Mirel DRÎMBĂ)"
copyright = "2023 Mănăstirea Călui"
