baseURL = 'https://manastirea-calui.ro'
languageCode = 'ro'
defaultcontentlanguage = "ro"
title = 'Mănăstirea Călui'
theme = 'manastirea-calui'
disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Manastirea Calui"
  description = "Mânăstirea Călui se află pe malul Oltețului, în apropiere de Craiova, nu departe de comuna Oboga, comuna renumită pentru ceramica ei populară."
  keywords = ["Manastirea Calui"]
  favicon = "favicon/favicon.ico"
  googleMapsLink = ""
  googleTagManager = "GTM-M36G9ND"
  robotsActive = "index, follow"
  googleBotActive = "index,follow,snippet,archive"
  BotsInactive = "noindex, nofollow"
  themeColorLight = "#000"
  themeColorDark = "#fff"

[params.footer]
  [params.footer.info]
  heading = "Investim în viitorul tău! <br>Proiect cofinanțat din Fondul European de Dezvoltare Regională prin Programul Operațional Regional 2014-2020"
  text = "Conținutul acestui material nu reprezintă în mod obligatoriu poziția oficială a Uniunii Europene sau a Guvernului României"
  
  [[params.footer.links]]
    title = "www.inforegio.ro"
    url = "https://www.inforegio.ro"

  [[params.footer.links]]
    title = "facebook.com/inforegio.ro"
    url = "https://facebook.com/inforegio.ro"

  [params.footer.contactInfo]
    address = "Şos. Frații Buzești nr. 209, sat Gura Căluiu, comuna Călui, judeţul Olt"
    street = "Şos. Frații Buzești nr. 209, sat Gura Căluiu, comuna Călui"
    city = "judeţul Olt"
    phone = "0249 / 421.026"
    fax = "0246 / 214.081"
    person = "Ieromonarh Macarie (Mirel DRÎMBĂ)"
    copyright = "2023 Mănăstirea Călui"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Acasă"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Istoric"
    url = "/istoric/"
    weight = 20

  [[menu.main]]
    name = "Proiect SMIS 117849"
    url = "/proiect-smis-117849/"
    weight = 30

  [[menu.main]]
    name = "Proiect SMIS 119469"
    url = "/proiect-smis-119469/"
    weight = 40

  [[menu.main]]
    name = "Galerie"
    url = "/galerie/"
    weight = 50

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 60
