baseURL = ''
languageCode = 'ro'
defaultcontentlanguage = "ro"
title = 'Mănăstirea Călui'
theme = 'manastirea-calui'
disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Manastirea Calui"
  description = ""
  keywords = ["Manastirea Calui"]
  favicon = "favicon/favicon.ico"
  googleMapsLink = ""
  googleTagManager = ""
  robotsActive = "index, follow"
  googleBotActive = "index,follow,snippet,archive"
  BotsInactive = "noindex, nofollow"
  themeColorLight = "#000"
  themeColorDark = "#fff"

[params.footer]
  [params.footer.contactInfo]
    address = "Şos. Frații Buzești nr. 209, sat Gura Căluiu, comuna Călui, judeţul Olt"
    phone = "0249 / 421.026"
    fax = "0246 / 214.081"
    person = "Ieromonarh Macarie (Mirel DRÎMBĂ)"
    copyright = "2023 Mănăstirea Călui"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Acasă"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Istoric"
    url = "/istoric/"
    weight = 20

  [[menu.main]]
    name = "Proiect 1"
    url = "/proiect1/"
    weight = 30

  [[menu.main]]
    name = "Proiect 2"
    url = "/proiect2/"
    weight = 40

  [[menu.main]]
    name = "Galerie"
    url = "/galerie/"
    weight = 50

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 60
