# Main Menu
[[main]]
name = "Acasă"
url = "/"
weight = 10

[[main]]
name = "Istoric"
url = "/istoric/"
weight = 20

[[main]]
name = "Proiect SMIS 117849"
url = "/proiect-smis-117849/"
weight = 30

[[main]]
name = "Proiect SMIS 119469"
url = "/proiect-smis-119469/"
weight = 40

[[main]]
name = "Galerie"
url = "/galerie/"
weight = 50

[[main]]
name = "Contact"
url = "/contact/"
weight = 60
