# Main Menu
[[main]]
name        = "Acasă"
url         = "/"
pre         = ""
post        = ""
title       = "Acasă"
parent      = ""
pageRef     = ""
identifier  = ""
weight      = 10

[[main]]
name        = "Istoric"
url         = ""
pre         = ""
post        = ""
title       = "Istoric"
parent      = ""
pageRef     = "/istoric"
identifier  = ""
weight      = 20

[[main]]
name        = "Proiect SMIS 117849"
url         = ""
pre         = ""
post        = ""
title       = "Proiect SMIS 117849"
parent      = ""
pageRef     = "/proiect1"
identifier  = ""
weight      = 30

[[main]]
name        = "Proiect SMIS 119469"
url         = ""
pre         = ""
post        = ""
title       = "Proiect SMIS 119469"
parent      = ""
pageRef     = "/proiect2"
identifier  = ""
weight      = 40

[[main]]
name        = "Digitalizare 3D"
url         = "https://arenacad.websharecloud.com/?v=pv&t=p:default,c:panoramaview,h:f,m:t,pr:t&pv=pv1&pv1=vt:3d,u:b86e6f7c-f0ca-42db-bf6c-0caedcd7d363,cf:111.00,dh:f,st:f,cx:-47.10516,cy:-9.92792,cz:111.54110,p:5.46697,t:-0.09227&p=p:digitizare-manastire-gura-calui"
pre         = ""
post        = ""
title       = "Digitalizare 3D"
parent      = ""
pageRef     = ""
identifier  = ""
weight      = 50

[[main]]
name        = "Galerie"
url         = ""
pre         = ""
post        = ""
title       = "Galerie"
parent      = ""
pageRef     = "/galerie"
identifier  = ""
weight      = 60

[[main]]
name        = "Contact"
url         = ""
pre         = ""
post        = ""
title       = "Contact"
parent      = ""
pageRef     = "/contact"
identifier  = ""
weight      = 70